# Generated by Django 5.0.2 on 2024-07-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0002_delete_articles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Назва")),
                ("full_text", models.TextField(verbose_name="Text")),
                ("education", models.CharField(max_length=50, verbose_name="Назва")),
                ("full_text_one", models.TextField(verbose_name="Text")),
                ("ability", models.CharField(max_length=50, verbose_name="Назва")),
                ("full_text_two", models.TextField(verbose_name="Text")),
            ],
        ),
    ]
