# Generated by Django 5.0.2 on 2024-07-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="c",
            new_name="Articles",
        ),
    ]
