# Generated by Django 5.0.2 on 2024-07-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_c_articles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articles",
            old_name="image_1",
            new_name="image1",
        ),
        migrations.RenameField(
            model_name="articles",
            old_name="image_2",
            new_name="image2",
        ),
        migrations.RenameField(
            model_name="articles",
            old_name="image_3",
            new_name="image3",
        ),
        migrations.RenameField(
            model_name="articles",
            old_name="image_4",
            new_name="image4",
        ),
        migrations.RenameField(
            model_name="articles",
            old_name="image_5",
            new_name="image5",
        ),
    ]
